# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'win1803'

strategy:
  parallel: 2
  matrix:
    TEST_SCENARIO_1:
      TEST_SCENARIO: 1
    TEST_SCENARIO_2:
      TEST_SCENARIO: 2

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  displayName: 'Install Node.js'

- script: |
    cinst GoogleChrome -y
  displayName: 'Install Chrome'

- script: |
    echo multiline npm isn't working
    npm install -g npm && npm install && npm test
  displayName: 'npm install and build'
