# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'win1803'

jobs:
- job: TEST_SCENARIO=1
  variables:
    TEST_SCENARIO: 1
- job: TEST_SCENARIO=2
  variables:
    TEST_SCENARIO: 2

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g npm
    npm --version
    npm install
    npm test
  displayName: 'npm install and build'
